source 'http://ruby.taobao.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git =g> 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'jquery-rails'

# authentication
gem 'devise'
gem 'cancan'

# form
gem 'simple_form'

# pagination
gem 'kaminari'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'bootstrap-sass', '~> 2.3.1.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  #gem "therubyracer"
  #gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
  #gem "twitter-bootstrap-rails"

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem "rspec-rails", "~> 2.0"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem 'quiet_assets'
end

group :test do
  gem "factory_girl_rails"
  gem "capybara"
  gem 'simplecov'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
